In [1]:
#importing libraries
import os
import glob
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
pd.set_option('display.max_columns', 500)

In [2]:
#loading csv file
#brazilian government expenses, including all the ones related to agriculture or land
#obtained from https://www.kaggle.com/vicentegsantos/brazil-gov-expenses
#the original file (Brazil_Gov_Exp_All - Formated.csv) was not in CSV format, so it was converted to Brazil.csv in Excel
gov_file = "./Resources/Brazil.csv"

In [4]:
#reading csv
gov_df = pd.read_csv(gov_file, encoding='ISO-8859-1')
gov_df.head()

,Year,Gov_agency_Cod,Sup_Gov_agency_Cod,Planned,Released,Gov_agency_Name,Sup_Gov_agency_Name,Paid_out
0,2014,20101,20000,"1.207.732.252,04","1.080.446.271,42",Presidencia da Republica,Presidencia da Republica,"1.073.206.586,35"
1,2014,20116,20000,"188.922.008,78","177.563.751,32",Fundo de Imprensa Nacional,Presidencia da Republica,"177.558.779,52"
2,2014,20122,81000,"87.360.033,22","30.141.173,42",Secretaria Nacional de Politicas para Mulheres,"Ministerio da Mulher, Familia e Direitos Humanos","30.127.407,52"
3,2014,20129,22000,"1.427.440.589,25","1.024.935.703,88",Secretaria Especial de Agricultura Familiar e ...,"Ministerio da Agricultura, Pecuaria e Abasteci...","1.022.675.533,51"
4,2014,20202,25000,"42.617.886,50","39.935.056,75",Fundacao Escola Nacional de Administracao Publica,Ministerio da Economia,"39.935.056,75"

In [5]:
#soy bean production/consupmtion totals per year, including global and brazilian numbers
#saved all the soy files to "soy" subfolder, and all the corn files to "corn" subfolder
#obtained from https://www.kaggle.com/ainslie/usda-wasde-monthly-corn-soybean-projections

#switching to soy directory (put all the soy files in "soy folder")
os.chdir("./Resources/soy_corn/soy")

#loading csv files
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [6]:
#combine all files in the list
combined_soy_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_soy_csv.to_csv( "combined_soy_csv.csv", index=False, encoding='utf-8-sig')

In [7]:
combined_soy_csv.head()

,Date,Area Planted,Area Harvested,Yield,Beginning Stocks,Production,Imports,Total Supply,Crushings,Exports,Seed,Residual,Total Use,Ending Stocks,World BeginningStocks,World Production,World Imports,World DomesticCrush,World DomesticTotal,World Exports,World EndingStocks,United States BeginningStocks,United States Production,United States Imports,United States DomesticCrush,United States DomesticTotal,United States Exports,United States EndingStocks,Argentina BeginningStocks,Argentina Production,Argentina Imports,Argentina DomesticCrush,Argentina DomesticTotal,Argentina Exports,Argentina EndingStocks,Brazil BeginningStocks,Brazil Production,Brazil Imports,Brazil DomesticCrush,Brazil DomesticTotal,Brazil Exports,Brazil EndingStocks,China BeginningStocks,China Production,China Imports,China DomesticCrush,China DomesticTotal,China Exports,China EndingStocks,Japan BeginningStocks,Japan Production,Japan Imports,Japan DomesticCrush,Japan DomesticTotal,Japan Exports,Japan EndingStocks,Mexico BeginningStocks,Mexico Production,Mexico Imports,Mexico DomesticCrush,Mexico DomesticTotal,Mexico Exports,Mexico EndingStocks,European Union BeginningStocks,European Union Production,European Union Imports,European Union DomesticCrush,European Union DomesticTotal,European Union Exports,European Union EndingStocks
0,2007/05/11,67.1,66.1,41.5,610.0,2745.0,4.0,3359.0,1790.0,1080.0,85.0,84.0,3039.0,320.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,2007/06/11,67.1,66.1,41.5,610.0,2745.0,4.0,3359.0,1790.0,1080.0,85.0,84.0,3039.0,320.0,63.60,225.32,74.89,203.43,234.28,75.53,54.00,16.59,74.71,0.11,48.72,53.31,29.39,8.70,22.06,47.0,1.15,38.5,40.10,8.6,21.51,18.54,61.0,0.06,29.3,32.28,29.69,17.63,3.43,15.6,34.5,39.7,50.00,0.45,3.08,0.27,0.23,4.15,2.93,4.33,0.0,0.32,0.04,0.1,3.88,3.94,3.98,0.0,0.04,1.02,1.05,14.88,14.44,15.89,0.05,1.01
2,2007/07/12,64.1,63.3,41.5,600.0,2625.0,4.0,3229.0,1800.0,1020.0,85.0,79.0,2985.0,245.0,64.17,222.05,75.31,203.44,234.17,75.49,51.87,16.34,71.44,0.11,48.99,53.47,27.76,6.67,22.93,47.0,1.80,38.5,40.08,10.2,21.46,18.54,61.0,0.06,29.3,32.28,29.69,17.63,3.43,15.6,34.5,39.7,50.00,0.45,3.08,0.27,0.23,4.15,2.93,4.33,0.0,0.32,0.04,0.1,3.95,4.01,4.05,0.0,0.04,1.02,1.05,14.88,14.44,15.89,0.05,1.01
3,2007/08/10,64.1,63.3,41.5,575.0,2625.0,4.0,3205.0,1800.0,1020.0,85.0,79.0,2985.0,220.0,64.52,221.62,74.09,202.80,233.21,75.38,51.63,15.66,71.45,0.11,48.99,53.47,27.76,5.99,23.55,47.0,1.80,38.5,40.08,10.2,22.07,18.54,61.0,0.06,29.3,32.28,29.69,17.63,3.18,15.2,33.5,38.2,48.45,0.35,3.08,0.27,0.23,4.15,2.93,4.33,0.0,0.32,0.04,0.1,3.95,4.01,4.05,0.0,0.04,1.79,1.05,14.88,15.30,16.75,0.05,0.92
4,2007/09/12,64.1,63.3,41.4,555.0,2619.0,6.0,3180.0,1825.0,975.0,85.0,79.0,2964.0,215.0,63.07,221.27,74.94,203.47,233.94,74.99,50.35,15.10,71.27,0.16,49.67,54.14,26.54,5.86,22.98,47.0,1.80,38.5,40.08,10.2,21.50,19.04,61.0,0.06,29.3,32.28,30.69,17.13,3.18,15.2,33.5,38.2,48.45,0.35,3.08,0.27,0.23,4.15,2.93,4.33,0.0,0.32,0.04,0.1,3.95,4.01,4.05,0.0,0.04,0.99,1.02,15.68,15.27,16.72,0.05,0.92

In [8]:
#Saving soy total values on global dataframe
combined_soy_csv_df = pd.DataFrame(combined_soy_csv)
combined_soy_global_df = combined_soy_csv_df[["Date", "Area Planted", "Yield", "Area Harvested", "Beginning Stocks", \
                                           "Production", "Imports", "Total Supply", "Crushings", "Exports"]]
combined_soy_global_df.head()

,Date,Area Planted,Yield,Area Harvested,Beginning Stocks,Production,Imports,Total Supply,Crushings,Exports
0,2007/05/11,67.1,41.5,66.1,610.0,2745.0,4.0,3359.0,1790.0,1080.0
1,2007/06/11,67.1,41.5,66.1,610.0,2745.0,4.0,3359.0,1790.0,1080.0
2,2007/07/12,64.1,41.5,63.3,600.0,2625.0,4.0,3229.0,1800.0,1020.0
3,2007/08/10,64.1,41.5,63.3,575.0,2625.0,4.0,3205.0,1800.0,1020.0
4,2007/09/12,64.1,41.4,63.3,555.0,2619.0,6.0,3180.0,1825.0,975.0

In [9]:
#Saving soy Brazilian values on Brazil dataframe
combined_soy_brazil_df = combined_soy_csv_df[["Date", "Brazil BeginningStocks","Brazil Production","Brazil Imports", \
                                              "Brazil DomesticTotal", "Brazil DomesticCrush","Brazil Exports", "Brazil EndingStocks"]]
combined_soy_brazil_df.head()

,Date,Brazil BeginningStocks,Brazil Production,Brazil Imports,Brazil DomesticTotal,Brazil DomesticCrush,Brazil Exports,Brazil EndingStocks
0,2007/05/11,0.00,0.0,0.00,0.00,0.0,0.00,0.00
1,2007/06/11,18.54,61.0,0.06,32.28,29.3,29.69,17.63
2,2007/07/12,18.54,61.0,0.06,32.28,29.3,29.69,17.63
3,2007/08/10,18.54,61.0,0.06,32.28,29.3,29.69,17.63
4,2007/09/12,19.04,61.0,0.06,32.28,29.3,30.69,17.13

In [10]:
#switching to corn directory (put all the soy files in "corn folder")
os.chdir("../corn")

In [11]:
#loading csv files
#corn production/consupmtion totals per year, including global and brazilian numbers
#obtained from https://www.kaggle.com/ainslie/usda-wasde-monthly-corn-soybean-projections
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
combined_corn_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_corn_csv.to_csv( "combined_corn_csv.csv", index=False, encoding='utf-8-sig')

In [12]:
combined_corn_csv.head()

,Date,Area Planted,Area Harvested,Yield,Beginning Stocks,Production,Imports,Total Supply,Feed and Residual,FSI,Ethanol,Total Domestic,Exports,Total Use,Ending Stocks,World BeginningStocks,World Production,World Imports,World DomesticFeed,World DomesticTotal,World Exports,World EndingStocks,United States BeginningStocks,United States Production,United States Imports,United States DomesticFeed,United States DomesticTotal,United States Exports,United States EndingStocks,Argentina BeginningStocks,Argentina Production,Argentina Imports,Argentina DomesticFeed,Argentina DomesticTotal,Argentina Exports,Argentina EndingStocks,Brazil BeginningStocks,Brazil Production,Brazil Imports,Brazil DomesticFeed,Brazil DomesticTotal,Brazil Exports,Brazil EndingStocks,China BeginningStocks,China Production,China Imports,China DomesticFeed,China DomesticTotal,China Exports,China EndingStocks,Japan BeginningStocks,Japan Production,Japan Imports,Japan DomesticFeed,Japan DomesticTotal,Japan Exports,Japan EndingStocks,Mexico BeginningStocks,Mexico Production,Mexico Imports,Mexico DomesticFeed,Mexico DomesticTotal,Mexico Exports,Mexico EndingStocks,South Korea BeginningStocks,South Korea Production,South Korea Imports,South Korea DomesticFeed,South Korea DomesticTotal,South Korea Exports,South Korea EndingStocks,South Africa BeginningStocks,South Africa Production,South Africa Imports,South Africa DomesticFeed,South Africa DomesticTotal,South Africa Exports,South Africa EndingStocks,Canada BeginningStocks,Canada Production,Canada Imports,Canada DomesticFeed,Canada DomesticTotal,Canada Exports,Canada EndingStocks,Ukraine BeginningStocks,Ukraine Production,Ukraine Imports,Ukraine DomesticFeed,Ukraine DomesticTotal,Ukraine Exports,Ukraine EndingStocks,Egypt BeginningStocks,Egypt Production,Egypt Imports,Egypt DomesticFeed,Egypt DomesticTotal,Egypt Exports,Egypt EndingStocks,Southeast Asia BeginningStocks,Southeast Asia Production,Southeast Asia Imports,Southeast Asia DomesticFeed,Southeast Asia DomesticTotal,Southeast Asia Exports,Southeast Asia EndingStocks,European Union BeginningStocks,European Union Production,European Union Imports,European Union DomesticFeed,European Union DomesticTotal,European Union Exports,European Union EndingStocks
0,2007/05/11,90.5,82.9,150.3,937.0,12460.0,15.0,13412.0,5700.0,4790.0,3400.0,10490.0,1975.0,12465.0,947.0,93.20,766.50,82.23,482.85,769.45,83.11,90.25,23.80,316.50,0.38,144.79,266.46,50.17,24.06,1.59,24.0,0.0,5.3,7.2,16.0,2.39,5.37,50.0,0.3,35.5,42.0,6.5,7.17,30.86,146.0,0.1,105.0,148.0,3.0,25.96,0.65,0.0,16.1,11.7,16.2,0.0,0.55,2.91,23.2,10.2,17.5,33.3,0.03,2.98,1.32,0.06,9.1,7.1,9.2,0.0,1.28,0.38,10.5,0.25,4.35,8.9,0.75,1.48,1.57,11.50,1.6,9.2,13.1,0.2,1.37,1.07,7.0,0.0,4.5,5.1,2.5,0.47,0.49,5.98,4.3,8.3,10.4,0.0,0.37,2.25,17.08,4.2,15.5,21.35,0.24,1.95,10.42,55.37,3.5,45.3,60.3,0.3,8.69
1,2007/06/11,90.5,82.9,150.3,987.0,12460.0,15.0,13462.0,5700.0,4790.0,3400.0,10490.0,1975.0,12465.0,997.0,94.68,767.96,82.33,484.13,770.84,83.11,91.80,25.07,316.50,0.38,144.79,266.46,50.17,25.33,1.46,24.0,0.0,5.2,7.1,16.0,2.36,5.37,50.0,0.3,35.5,42.0,6.5,7.17,30.86,146.0,0.1,105.0,148.0,3.0,25.96,0.65,0.0,16.1,11.7,16.2,0.0,0.55,2.91,23.2,10.2,17.5,33.3,0.03,2.98,1.32,0.06,9.1,7.1,9.2,0.0,1.28,0.38,10.5,0.25,4.35,8.9,0.75,1.48,1.57,11.50,1.6,9.2,13.1,0.2,1.37,1.07,7.5,0.0,5.0,5.6,2.5,0.47,0.49,5.98,4.3,8.3,10.4,0.0,0.37,2.25,17.08,4.2,15.5,21.35,0.24,1.95,10.72,55.72,3.5,45.8,60.8,0.3,8.84
2,2007/07/12,92.9,85.4,150.3,1137.0,12840.0,15.0,13992.0,5700.0,4790.0,3400.0,10490.0,2000.0,12490.0,1502.0,100.95,777.10,82.33,483.63,769.70,82.75,108.36,28.88,326.15,0.38,144.79,266.46,50.80,38.15,1.46,24.0,0.0,5.2,7.1,16.0,2.36,5.37,50.0,0.3,35.5,42.0,6.5,7.17,32.86,148.0,0.1,105.0,148.0,3.0,29.96,0.65,0.0,16.1,11.7,16.2,0.0,0.55,2.91,23.2,10.2,17.5,33.3,0.03,2.98,1.32,0.06,9.1,7.1,9.2,0.0,1.28,0.71,10.5,0.25,4.35,8.9,0.75,1.81,1.44,11.20,1.6,8.7,12.6,0.2,1.44,1.07,6.5,0.0,5.0,5.6,1.5,0.47,0.49,5.98,4.3,8.3,10.4,0.0,0.37,2.27,17.08,4.2,15.5,21.35,0.24,1.97,10.72,55.23,3.5,45.8,60.8,0.3,8.35
3,2007/08/10,92.9,85.4,152.8,1137.0,13054.0,15.0,14206.0,5750.0,4790.0,3400.0,10540.0,2150.0,12690.0,1516.0,100.20,771.50,85.33,483.25,769.48,86.01,102.23,28.88,331.58,0.38,146.06,267.73,54.61,38.50,1.16,24.0,0.0,5.2,7.1,16.0,2.06,4.37,50.0,0.3,35.5,42.0,7.0,5.67,32.86,148.0,0.1,105.0,148.0,3.0,29.96,0.65,0.0,16.1,11.7,16.2,0.0,0.55,2.91,23.2,10.2,17.5,33.3,0.03,2.98,1.32,0.06,9.1,7.1,9.2,0.0,1.28,0.71,10.5,0.25,4.35,8.9,0.75,1.81,1.44,11.20,1.6,8.7,12.6,0.2,1.44,1.07,6.5,0.0,5.0,5.6,1.5,0.47,0.69,5.98,4.5,8.6,10.7,0.0,0.47,2.22,17.08,4.2,15.5,21.35,0.24,1.92,10.72,48.43,6.0,45.8,60.8,0.3,4.05
4,2007/09/12,92.9,85.4,155.8,1142.0,13308.0,15.0,14465.0,5850.0,4690.0,3300.0,10540.0,2250.0,12790.0,1675.0,100.96,774.10,87.93,486.06,769.62,88.55,105.44,29.01,338.04,0.38,148.60,267.73,57.15,42.55,1.16,22.5,0.0,4.8,6.7,16.0,0.96,3.67,51.0,0.3,35.5,42.0,7.0,5.97,32.56,147.0,0.1,105.0,148.0,3.0,28.66,1.15,0.0,16.1,11.7,16.2,0.0,1.05,3.21,23.2,10.2,17.5,33.3,0.03,3.28,1.32,0.06,9.1,7.1,9.2,0.0,1.28,0.91,10.5,0.25,4.35,8.9,0.75,2.01,1.49,10.57,1.7,8.2,12.1,0.2,1.46,1.07,6.5,0.0,5.0,5.6,1.5,0.47,0.69,5.98,4.5,8.6,10.7,0.0,0.47,2.13,17.03,4.2,15.5,21.35,0.24,1.77,10.62,46.94,8.0,46.5,61.5,0.3,3.76

In [13]:
#Saving corn total values on global dataframe
combined_corn_csv_df = pd.DataFrame(combined_corn_csv)
combined_corn_global_df = combined_corn_csv_df[["Date", "Area Planted", "Yield", "Area Harvested", "Beginning Stocks", \
                                           "Production", "Imports", "Total Supply", "Feed and Residual", "Exports"]]
combined_corn_global_df.head()

,Date,Area Planted,Yield,Area Harvested,Beginning Stocks,Production,Imports,Total Supply,Feed and Residual,Exports
0,2007/05/11,90.5,150.3,82.9,937.0,12460.0,15.0,13412.0,5700.0,1975.0
1,2007/06/11,90.5,150.3,82.9,987.0,12460.0,15.0,13462.0,5700.0,1975.0
2,2007/07/12,92.9,150.3,85.4,1137.0,12840.0,15.0,13992.0,5700.0,2000.0
3,2007/08/10,92.9,152.8,85.4,1137.0,13054.0,15.0,14206.0,5750.0,2150.0
4,2007/09/12,92.9,155.8,85.4,1142.0,13308.0,15.0,14465.0,5850.0,2250.0

In [14]:
#Saving corn Brazilian values on Brazil dataframe
combined_corn_brazil_df = combined_corn_csv_df[["Date", "Brazil BeginningStocks","Brazil Production","Brazil Imports", \
                                              "Brazil DomesticTotal", "Brazil DomesticFeed","Brazil Exports", "Brazil EndingStocks"]]
combined_corn_brazil_df.head()

,Date,Brazil BeginningStocks,Brazil Production,Brazil Imports,Brazil DomesticTotal,Brazil DomesticFeed,Brazil Exports,Brazil EndingStocks
0,2007/05/11,5.37,50.0,0.3,42.0,35.5,6.5,7.17
1,2007/06/11,5.37,50.0,0.3,42.0,35.5,6.5,7.17
2,2007/07/12,5.37,50.0,0.3,42.0,35.5,6.5,7.17
3,2007/08/10,4.37,50.0,0.3,42.0,35.5,7.0,5.67
4,2007/09/12,3.67,51.0,0.3,42.0,35.5,7.0,5.97

In [ ]:
#uploading
engine = create_engine('postgresql://sqladmin:password@localhost:5432/brazil_etl')
combined_soy_brazil_df.to_sql('combined_soy_brazil', engine, if_exists='replace', index=False)

In [19]:
#uploading do postgres sql db
engine = create_engine('postgresql://sqladmin:password@localhost:5432/brazil_etl')
combined_soy_brazil_df.to_sql('combined_soy_brazil', engine, if_exists='replace', index=False)

In [20]:
engine = create_engine('postgresql://sqladmin:password@localhost:5432/brazil_etl')
gov_df.to_sql('gov_expenses_brazil', engine, if_exists='replace', index=False)

In [21]:
engine = create_engine('postgresql://sqladmin:password@localhost:5432/brazil_etl')
combined_corn_brazil_df.to_sql('combined_corn_brazil', engine, if_exists='replace', index=False)

# APPENDIX 
##Additional Data sources that would help the analysis but were not loaded in the database for this exercise

In [13]:
#loading csv file
#corn bean price totals per month
#obtained from https://www.kaggle.com/ainslie/usda-wasde-monthly-corn-soybean-projections
#the original file was not in CSV format, so it was converted to csv in Excel
corn_price_file = "./Resources/corn_nearby.csv"

In [14]:
#reading csv
corn_price_df = pd.read_csv(corn_price_file, encoding='ISO-8859-1')
corn_price_df.head()

      dates  nearby_close
0  2/4/2008        510.50
1  2/5/2008        509.25
2  2/6/2008        501.50
3  2/7/2008        499.50
4  2/8/2008        508.00

In [15]:
#loading csv file
#soy bean price totals per month
#obtained from https://www.kaggle.com/ainslie/usda-wasde-monthly-corn-soybean-projections
#the original file was not in CSV format, so it was converted to csv in Excel
soy_price_file = "./Resources/soybean_nearby.csv"

In [16]:
#reading csv
soy_price_df = pd.read_csv(soy_price_file, encoding='ISO-8859-1')
soy_price_df.head()

      dates  nearby_close
0  2/4/2008        1326.0
1  2/5/2008        1323.0
2  2/6/2008        1318.5
3  2/7/2008        1331.5
4  2/8/2008        1339.0

In [17]:
#loading csv file
#Forest Fire Count per State in Brazil
#obtained from https://www.kaggle.com/gustavomodelli/forest-fires-in-brazil
forest_fire_count_file = "./Resources/forest_fire_amazon.csv"

In [18]:
#reading csv
forest_fire_count_df = pd.read_csv(forest_fire_count_file, encoding='ISO-8859-1', sep = ",")
forest_fire_count_df.head()

   year state    month  number        date
0  1998  Acre  Janeiro     0.0  1998-01-01
1  1999  Acre  Janeiro     0.0  1999-01-01
2  2000  Acre  Janeiro     0.0  2000-01-01
3  2001  Acre  Janeiro     0.0  2001-01-01
4  2002  Acre  Janeiro     0.0  2002-01-01

In [ ]:
#uploading do postgres sql db
engine = create_engine('postgresql://sqladmin:password@localhost:5432/brazil_etl')
soy_price_df.to_sql('soy_price', engine, if_exists='replace', index=False)

In [ ]:
engine = create_engine('postgresql://sqladmin:password@localhost:5432/brazil_etl')
corn_price_df.to_sql('corn_price', engine, if_exists='replace', index=False)

In [ ]:
engine = create_engine('postgresql://sqladmin:password@localhost:5432/brazil_etl')
forest_fire_count_df.to_sql('forest_fire_count', engine, if_exists='replace', index=False)